Project completed
AHeisenberg/java-filmorate pull request #16
Opened 2022-07-27 08:14 UTC by madromk

2022-07-27 14:13 UTC, Fleaman777 requested changes

2022-07-27 14:13 UTC, Fleaman777 commented on README.md
>  Template repository for Filmorate project.
ребята привет,
в ридми нужно дбавить список фичей которые вы сделали, 
так  буду знать, что проверять :)

2022-07-27 16:41 UTC, madromk commented on README.md
>  Template repository for Filmorate project.
принято. сделано )

2022-07-28 08:54 UTC, Fleaman777 requested changes
Ребята привет. 

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы. 
У вас очень круто все получилось. Есть, конечно, что поправить, но ничего глобального, в основном какие-то косметические моменты. 
Очень понравились ваши запросы, составлены грамотно и оптимально, для самого начала карьеры - это достойный уровень. Сама логика в сервисах, тоже на отлично, так же как и контроллеры
Так держать 💪🏼

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (sortBy.equals("year")) {
а почему бы нам просто не создать 1 метод сервиса getSortedFilmsByDirector(long id, String sortBy), а в этом методе использовать filmStorage.getAllFilmsByDirector(id, sortBy), 

все равно в каждом перегруженном методе сервиса  getAllFilmsByDirectorSortedBy... используется один и тот же метод стореджа

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                                      @RequestParam Optional<Integer> year) {
не вижу тут большого смысла использовать Optional в реквест параметрах, 
можно исползьовать примитивы и сравнивать с 0 или классы обертки и просто сравнивать с null, 

Optional немного загромождает восприятие

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                .orElseGet(() -> new ResponseEntity<>(null, HttpStatus.NOT_FOUND))).orElseGet(() -> new ResponseEntity<>(filmService.getTopLikableFilms(count), HttpStatus.OK)));
такая длинная цепочка .map...orElseGet() - сильно затрудняет понимание, что именно будет возвращено и в каком случае, 

попробуйте часть логики перенести в сервис 
или сделать ее через проброс исключений

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<Optional<Review>> addReview(@RequestBody Review review) {
лучше из контроллера не возвращать Optional,

Optional класс обертка, которая помогает безопасно работать с объектами внутри приложения, а наружу лучше отдавать готовый, ничем не оберенутый, объект

но возможно я чего-то не знаю, 
если у вас есть аргумент в пользу возвращения Optional из контроллера, то хорошо, ничего  не надо будет менять  :)

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @DeleteMapping("/{id}/Dislike/{userId}")
dislike должен быть с маленькой буквы

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        }
этот forech можно сделать через стрим, 

предыдущий, в целом, выглдяит неплохо, но тоже можно попробовать преобразовать, возможно получится еще аккуратней

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        for (var fst_entry : allLikes.entrySet()) {
название локальной переменной не совсем по джава код стайлу

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(reviewId);
не совсем понял, зачем нужно доставать review по id, если оно потом в методе никак не используется 

аналагично и в др методах ниже

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Set<Director> setDirectorsToFilm(long id) {
не совсем верное название метода, 
т.к. он скорее возвращает список режиссеров, чем его устанавливает, 

а если в названии set обозначает, что метод возвращает Set режиссеров, то это тоже неверно, т.к. в методе должен присутствовать глагол обозначающий действие метода

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private static final String SQL_DIRECTORS_FILM_BY_ID = "SELECT f.*, fd.director_id FROM films AS f " +
хорошо было бы в название добавить OREDER, что бы понимать, к чему именно относится BY 

аналагично в запросах ниже

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private static final String SQL_GET_TOP_LIKEBLE_FILMS = "SELECT * FROM films ORDER BY likes_count DESC LIMIT ?";
опечатка LIKEABLE

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
ооочень грамотные запросы, 
молодцы! 

и составлены хорошо и выглядят отлично

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
хороший стрим

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        }
этот foreach тоже хороший кандидат на стрим подход

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        }
у этих if-else есть общая часть, которую можно было бы вынести в приватный метод

2022-07-28 08:54 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    JdbcTemplate jdbcTemplate;
поле должно быть private

2022-07-29 14:06 UTC, fickt commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(reviewId);
А это валидация, если метод отработает, значит ревью с таким ID есть, если нет, то вылетит Exception

2022-07-30 10:20 UTC, Fleaman777 requested changes
Отличные исправления! Осталось пару незначительных моментов и можно будет принять работу

2022-07-30 10:20 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private List<Film> getTopLikableFilms(long count) {
лучше сначала в классе размещать публичные методы, что бы понимать какое апи у класса, а затем уже вспомогательные приватные методы

2022-07-30 10:20 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    .collect(Collectors.toList()).get(0);
вот этот стрим можно было бы вынести в отдельный метод

2022-08-01 09:06 UTC, Fleaman777 approved these changes
Все отлично.
Можно еще раз однозначно сказать, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении и в новой карьере

2022-08-01 10:38 UTC, merged