feat: added functionality to the specifications of the 9th Sprint
AHeisenberg/java-filmorate pull request #2
Opened 2022-06-16 06:59 UTC by AHeisenberg

2022-06-16 07:01 UTC, AHeisenberg commented
feat: added functionality to the specifications of the 9th Sprint

2022-06-16 21:12 UTC, kukolev requested changes

2022-06-16 21:12 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler({UserNotFoundException.class, FilmNotFoundException.class, FriendNotFoundException.class, LikeNotFoundException.class})
Лучше переименовать свой класс ExceptionHandler и тогда не придется прописывать весь путь в названии аннотации.

2022-06-16 21:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//        userController.add(user);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-16 21:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//    @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-17 06:56 UTC, AHeisenberg commented
fix: changes made according to Sprint 9 code review

2022-06-17 07:56 UTC, kukolev approved these changes

2022-06-17 08:23 UTC, merged