feat: added functionality to the specifications of the 10th Sprint
AHeisenberg/java-filmorate pull request #3
Opened 2022-07-03 11:32 UTC by AHeisenberg

2022-07-16 13:28 UTC, AHeisenberg commented
feat: added functionality to the specifications of the 11th Sprint

2022-07-17 07:40 UTC, kukolev requested changes

2022-07-17 07:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "INSERT INTO films(name, description, duration, release_date, rating_id) " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 07:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        String sql = "INSERT INTO genres(name) VALUES (?)";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 07:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MPADbStorage.java
> +        String sql = "INSERT INTO ratings_mpa(name) VALUES (?)";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 07:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "INSERT INTO users(email, login, name, birthday) " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 10:36 UTC, AHeisenberg commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "INSERT INTO users(email, login, name, birthday) " +
Здравствуйте, спасибо за комментарии, исправлено!

2022-07-17 12:56 UTC, kukolev requested changes

2022-07-17 12:56 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public static final String SQL_ADD_FILM = "INSERT INTO films(name, description, duration, release_date, rating_id) " +
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

2022-07-17 12:56 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public static final String SQL_ADD_GENRE = "INSERT INTO genres(name) VALUES (?)";
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

2022-07-17 12:56 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MPADbStorage.java
> +    public static final String SQL_ADD_RATING = "INSERT INTO ratings_mpa(name) VALUES (?)";
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

2022-07-17 12:56 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public static final String SQL_ADD_USER = "INSERT INTO users(email, login, name, birthday) " +
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

2022-07-17 13:54 UTC, AHeisenberg commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public static final String SQL_ADD_USER = "INSERT INTO users(email, login, name, birthday) " +
Действительно!

2022-07-18 07:24 UTC, kukolev requested changes

2022-07-18 07:24 UTC, kukolev commented on db/filmorate.trace.db
> +2022-07-12 15:43:47 jdbc[3]: exception
Этот файл не относится к исходному коду проекта и не нужен здесь. Файл нужно удалить.

Также нужно удалить файл filmorate.mv.db по той-же причине.

2022-07-18 07:43 UTC, AHeisenberg commented on db/filmorate.trace.db
> +2022-07-12 15:43:47 jdbc[3]: exception
Здравствуйте Александр, файл filmorate.mv.db появляется после запуска приложения и я хотел бы его оставить, если это не критично...  db/filmorate.trace.db  удален.

2022-07-18 11:25 UTC, kukolev commented on db/filmorate.trace.db
> +2022-07-12 15:43:47 jdbc[3]: exception
Андрей, вот именно потому, что файл появляется после запуска он и не нужен в исходном коде. Файл можно оставить у себя локально, но вот коммитить его это совершенно лишнее. Удалите, его, пожалуйста и не комитьте.

2022-07-18 12:11 UTC, AHeisenberg commented on db/filmorate.trace.db
> +2022-07-12 15:43:47 jdbc[3]: exception
Спасибо за пояснения, удалил!

2022-07-19 07:23 UTC, kukolev approved these changes

2022-07-19 07:38 UTC, merged